name: Release plugin

on:
  push:
    tags:
    - '*'

env:
  PLUGIN_NAME: obsidian-ghost-text

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Build
      id: build
      run: |
        npm install
        npm run build

    - name: Test
      id: test
      run: |
        npm run tests

    - name: Bundle
      id: bundle
      run: |
        TAG_NAME=$(git tag --sort version:refname | tail -n 1)
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        mkdir ${{ env.PLUGIN_NAME }}
        cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}-${TAG_NAME}.zip ${{ env.PLUGIN_NAME }}
        ls

    - name: Get release notes
      id: release_notes
      run: |
        TAG_NAME="${{ steps.bundle.outputs.tag_name }}"
        CLEAN_TAG=$(echo "$TAG_NAME" | sed -E 's/^v//; s/-.*//')
        
        CHANGELOG=$(sed -n -e "/## $TAG_NAME/,/## /p" CHANGELOG.md | sed '/## /d')
        
        if [ -z "$CHANGELOG" ]; then
          CHANGELOG=$(sed -n -e "/## $CLEAN_TAG/,/## /p" CHANGELOG.md | sed '/## /d')
        fi
        
        if [ -z "$CHANGELOG" ]; then  
          echo "No release notes found for $TAG_NAME in CHANGELOG.md, using default message."
          CHANGELOG="No release notes provided for this version."
        fi  
        
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ github.token }}
        files: |
          ${{ env.PLUGIN_NAME }}-${{ steps.bundle.outputs.tag_name }}.zip
          main.js
          manifest.json
          styles.css
        body: ${{ steps.release_notes.outputs.body }}

